site_name: MomentEmu Documentation
site_description: A lightweight, interpretable polynomial emulator with auto-differentiation support
site_author: Zheng Zhang
site_url: https://zzhang0123.github.io/MomentEmu/

repo_name: zzhang0123/MomentEmu
repo_url: https://github.com/zzhang0123/MomentEmu
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Installation:
    - Quick Start: installation/quick-start.md
    - Auto-Differentiation: installation/autodiff.md
    - Development Setup: installation/development.md
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
    - Forward Emulation: tutorials/forward-emulation.md
    - Inverse Emulation: tutorials/inverse-emulation.md
    - Auto-Differentiation Guide: tutorials/autodiff-guide.md
  - API Reference:
    - Core Module: api/core.md
    - JAX Integration: api/jax.md
    - PyTorch Integration: api/torch.md
    - SymPy Integration: api/symbolic.md
  - Theory:
    - Mathematical Background: theory/mathematical-background.md
    - Moment Matrices: theory/moment-matrices.md
    - Polynomial Approximation: theory/polynomial-approximation.md
  - Examples:
    - Use Cases: examples/use-cases.md
    - Performance Benchmarks: examples/benchmarks.md
    - External Examples: examples/polycamb.md
  - Contributing:
    - Development Guide: contributing/development.md
    - Testing: contributing/testing.md
    - Package Configuration: contributing/package-config.md
    - Documentation Setup: contributing/documentation-setup.md
    - Release Process: contributing/release-process.md
